blank_issues_enabled: true
contact_links:
  - name: GitHub Discussions
    url: https://github.com/whallin/.github/discussions
    about: Ask questions and discuss ideas with me
  - name: Personal Website
    url: https://hallin.media/
    about: Learn more about me and my projects
  - name: Contact me directly
    url: https://hallin.media/contact
    about: Get in touch with me directly
